const mongoose=require('mongoose');

const noteSchema = new mongoose.Schema({
    title:{
        type:String,
        required:true
    },
    content:{
        type:String,
        default:""
    },
    tags:[String],
    sourceType:{
        type:String,
        enum:["text","image"],
        default:"text"
    },
    imagePath:{
        type:String,
        default:""
    },
    imageUrl:{
        type:String,
        default:""
    },
    originalFilename:{
        type:String,
        default:""
    },
    processingStatus:{
        type:String,
        enum:["pending","processed","needs_review"],
        default:"processed"
    },
    ocrText:{
        type:String,
        default:""
    },
    ocrBlocks:{
        type:Array,
        default:[]
    },
    ocrConfidence:{
        type:Number,
        default:null
    },
    aiDraft:{
        type:String,
        default:""
    },
    createdAt:{
        type:Date,
        default:Date.now
    },   
},{timestamps:true});

module.exports=mongoose.model('Note',noteSchema);